
import { Language, Mission, Badge, PracticeQuestion } from './types';

export const LANGUAGES_CONFIG = [
  {
    id: Language.PYTHON,
    icon: '🐍',
    color: 'bg-blue-500',
    description: 'Chinh phục 10 cấp độ từ lập trình viên tập sự đến Bậc Thầy Python.',
  },
  {
    id: Language.HTML,
    icon: '🌐',
    color: 'bg-red-500',
    description: 'Xây dựng cấu trúc web hiện đại và đạt danh hiệu Vô Địch thiết kế.',
  },
];

export const RANK_BADGES: Record<string, Badge> = {
  gold: { id: 'gold_champion', name: 'Huy hiệu Vàng: Vô Địch', icon: '🏆', tier: 'gold', description: 'Đạt trên 5000 điểm XP - Bậc thầy tối thượng' },
  silver: { id: 'silver_master', name: 'Huy hiệu Bạc: Cao Thủ', icon: '🥈', tier: 'silver', description: 'Đạt từ 3000 đến 5000 điểm XP - Chuyên gia' },
  bronze: { id: 'bronze_warrior', name: 'Huy hiệu Đồng: Chiến Binh', icon: '🥉', tier: 'bronze', description: 'Đạt từ 2000 đến 3000 điểm XP - Đang phát triển' },
};

export const INITIAL_BADGES: Badge[] = [
  { id: 'first_step', name: 'Bước chân đầu tiên', icon: '👣', description: 'Hoàn thành nhiệm vụ đầu tiên' },
  ...Object.values(RANK_BADGES)
];

export const PRACTICE_QUESTION_BANK: Record<Language, Record<number, PracticeQuestion[]>> = {
  [Language.PYTHON]: {
    1: [
      { id: 'py_l1_1', question: 'Lệnh nào dùng để in dữ liệu ra màn hình trong Python?', options: ['A. input()', 'B. print()', 'C. out()', 'D. write()'], correctOption: 1 },
      { id: 'py_l1_2', question: 'Đâu là cách đặt tên biến đúng trong Python?', options: ['A. 1variable', 'B. my-variable', 'C. my_variable', 'D. my variable'], correctOption: 2 },
      { id: 'py_l1_3', question: 'Kiểu dữ liệu của 10.5 là gì?', options: ['A. int', 'B. string', 'C. float', 'D. boolean'], correctOption: 2 },
      { id: 'py_l1_4', question: 'Ký hiệu nào dùng để ghi chú (comment) một dòng trong Python?', options: ['A. //', 'B. /*', 'C. #', 'D. <!--'], correctOption: 2 },
      { id: 'py_l1_5', question: 'Kết quả của 2 ** 3 là bao nhiêu?', options: ['A. 6', 'B. 8', 'C. 9', 'D. 5'], correctOption: 1 },
      { id: 'py_l1_6', question: 'Hàm type() dùng để làm gì?', options: ['A. In dữ liệu', 'B. Nhập dữ liệu', 'C. Kiểm tra kiểu dữ liệu', 'D. Chuyển đổi dữ liệu'], correctOption: 2 },
      { id: 'py_l1_7', question: 'Đâu là kiểu dữ liệu logic (đúng/sai)?', options: ['A. string', 'B. float', 'C. int', 'D. bool'], correctOption: 3 },
      { id: 'py_l1_8', question: 'Làm thế nào để tạo một chuỗi văn bản?', options: ['A. Dùng dấu ngoặc đơn hoặc kép', 'B. Dùng dấu ngoặc nhọn', 'C. Dùng dấu ngoặc vuông', 'D. Không cần dấu ngoặc'], correctOption: 0 },
      { id: 'py_l1_9', question: 'Kết quả của "Hello" + "World" là gì?', options: ['A. HelloWorld', 'B. Hello World', 'C. Hello+World', 'D. Lỗi'], correctOption: 0 },
      { id: 'py_l1_10', question: 'Giá trị của x sau lệnh x = 5; x = x + 2 là?', options: ['A. 5', 'B. 2', 'C. 7', 'D. 10'], correctOption: 2 },
      { id: 'py_l1_11', question: 'Python là ngôn ngữ lập trình loại nào?', options: ['A. Biên dịch', 'B. Thông dịch', 'C. Ngôn ngữ máy', 'D. Hợp ngữ'], correctOption: 1 },
      { id: 'py_l1_12', question: 'Hàm input() luôn trả về kiểu dữ liệu nào?', options: ['A. int', 'B. float', 'C. str', 'D. bool'], correctOption: 2 },
      { id: 'py_l1_13', question: 'Ký hiệu nào dùng để gán giá trị cho biến?', options: ['A. ==', 'B. =', 'C. :=', 'D. ->'], correctOption: 1 },
      { id: 'py_l1_14', question: 'Lệnh print(10 // 3) cho kết quả là?', options: ['A. 3.33', 'B. 3', 'C. 1', 'D. 0'], correctOption: 1 },
      { id: 'py_l1_15', question: 'Lệnh print(10 % 3) cho kết quả là?', options: ['A. 3', 'B. 1', 'C. 0', 'D. 10'], correctOption: 1 },
      { id: 'py_l1_16', question: 'Python do ai tạo ra?', options: ['A. Mark Zuckerberg', 'B. Guido van Rossum', 'C. Bill Gates', 'D. Steve Jobs'], correctOption: 1 },
      { id: 'py_l1_17', question: 'Đâu là từ khóa trong Python?', options: ['A. variable', 'B. print', 'C. if', 'D. hello'], correctOption: 2 },
      { id: 'py_l1_18', question: 'Kiểu dữ liệu của True là?', options: ['A. string', 'B. int', 'C. bool', 'D. None'], correctOption: 2 },
      { id: 'py_l1_19', question: 'Hàm int("123") sẽ trả về giá trị gì?', options: ['A. "123"', 'B. 123', 'C. 123.0', 'D. Lỗi'], correctOption: 1 },
      { id: 'py_l1_20', question: 'Thứ tự ưu tiên toán tử nào đúng?', options: ['A. Cộng -> Nhân', 'B. Nhân -> Cộng', 'C. Trừ -> Nhân', 'D. Như nhau'], correctOption: 1 },
    ],
    2: [
      { id: 'py_l2_1', question: 'Lệnh if dùng để làm gì?', options: ['A. Lặp lại công việc', 'B. Kiểm tra điều kiện', 'C. Định nghĩa hàm', 'D. Nhập dữ liệu'], correctOption: 1 },
      { id: 'py_l2_2', question: 'Toán tử so sánh "bằng" trong Python là?', options: ['A. =', 'B. ==', 'C. ===', 'D. equals'], correctOption: 1 },
      { id: 'py_l2_3', question: 'Kết quả của 5 > 3 and 2 < 1 là?', options: ['A. True', 'B. False', 'C. None', 'D. Error'], correctOption: 1 },
      { id: 'py_l2_4', question: 'Lệnh elif là viết tắt của từ nào?', options: ['A. else if', 'B. every if', 'C. each if', 'D. end if'], correctOption: 0 },
      { id: 'py_l2_5', question: 'Để kiểm tra điều kiện ngược lại của if ta dùng?', options: ['A. otherwise', 'B. else', 'C. then', 'D. final'], correctOption: 1 },
      { id: 'py_l2_6', question: 'Toán tử "khác" trong Python là?', options: ['A. <>', 'B. !=', 'C. not=', 'D. !=='], correctOption: 1 },
      { id: 'py_l2_7', question: 'Dấu nào dùng để bắt đầu khối lệnh sau if?', options: ['A. {', 'B. ;', 'C. :', 'D. ('], correctOption: 2 },
      { id: 'py_l2_8', question: 'Python sử dụng gì để phân biệt các khối lệnh?', options: ['A. Dấu ngoặc nhọn', 'B. Dấu chấm phẩy', 'C. Thụt đầu dòng (Indentation)', 'D. Dấu ngoặc đơn'], correctOption: 2 },
      { id: 'py_l2_9', question: 'Kết quả của not True là?', options: ['A. True', 'B. False', 'C. None', 'D. 0'], correctOption: 1 },
      { id: 'py_l2_10', question: 'Để kiểm tra một giá trị có nằm trong danh sách không ta dùng?', options: ['A. is', 'B. in', 'C. has', 'D. contains'], correctOption: 1 },
      { id: 'py_l2_11', question: 'Toán tử logic "hoặc" trong Python là?', options: ['A. ||', 'B. or', 'C. |', 'D. OR'], correctOption: 1 },
      { id: 'py_l2_12', question: 'Lệnh if 0: sẽ được xử lý như thế nào?', options: ['A. Luôn đúng', 'B. Luôn sai', 'C. Lỗi', 'D. Tùy máy tính'], correctOption: 1 },
      { id: 'py_l2_13', question: 'Lệnh if "Hello": sẽ được xử lý như thế nào?', options: ['A. Luôn đúng', 'B. Luôn sai', 'C. Lỗi', 'D. Trả về None'], correctOption: 0 },
      { id: 'py_l2_14', question: 'Kết quả của 10 >= 10 là?', options: ['A. True', 'B. False', 'C. 10', 'D. 0'], correctOption: 0 },
      { id: 'py_l2_15', question: 'Câu lệnh if lồng nhau là gì?', options: ['A. Nhiều if cạnh nhau', 'B. Một if nằm trong một if khác', 'C. Lệnh if không có else', 'D. Lệnh if có nhiều điều kiện'], correctOption: 1 },
      { id: 'py_l2_16', question: 'Để thoát khỏi vòng lặp ngay lập tức, ta dùng?', options: ['A. stop', 'B. break', 'C. exit', 'D. finish'], correctOption: 1 },
      { id: 'py_l2_17', question: 'Vòng lặp nào dùng khi biết trước số lần lặp?', options: ['A. while', 'B. for', 'C. repeat', 'D. loop'], correctOption: 1 },
      { id: 'py_l2_18', question: 'Hàm range(5) sẽ tạo ra các số nào?', options: ['A. 1, 2, 3, 4, 5', 'B. 0, 1, 2, 3, 4', 'C. 0, 1, 2, 3, 4, 5', 'D. 5, 4, 3, 2, 1'], correctOption: 1 },
      { id: 'py_l2_19', question: 'Lệnh continue dùng để làm gì?', options: ['A. Thoát vòng lặp', 'B. Bỏ qua lần lặp hiện tại', 'C. Dừng chương trình', 'D. Chạy lại từ đầu'], correctOption: 1 },
      { id: 'py_l2_20', question: 'Vòng lặp vô hạn xảy ra khi nào?', options: ['A. Điều kiện luôn đúng', 'B. Điều kiện luôn sai', 'C. Không có điều kiện', 'D. Có lệnh break'], correctOption: 0 },
    ],
    3: [
      { id: 'py_l3_1', question: 'Cách tạo một danh sách (List) trong Python?', options: ['A. (1, 2)', 'B. {1, 2}', 'C. [1, 2]', 'D. <1, 2>'], correctOption: 2 },
      { id: 'py_l3_2', question: 'Phần tử đầu tiên của danh sách có chỉ số là bao nhiêu?', options: ['A. 1', 'B. 0', 'C. -1', 'D. First'], correctOption: 1 },
      { id: 'py_l3_3', question: 'Để thêm phần tử vào cuối danh sách, ta dùng?', options: ['A. add()', 'B. push()', 'C. append()', 'D. insert()'], correctOption: 2 },
      { id: 'py_l3_4', question: 'Hàm len() dùng để làm gì?', options: ['A. Xóa danh sách', 'B. Đếm số phần tử', 'C. Sắp xếp danh sách', 'D. Đảo ngược danh sách'], correctOption: 1 },
      { id: 'py_l3_5', question: 'Để xóa phần tử theo giá trị, ta dùng lệnh?', options: ['A. del', 'B. remove()', 'C. pop()', 'D. clear()'], correctOption: 1 },
      { id: 'py_l3_6', question: 'Lệnh my_list[1:3] thực hiện việc gì?', options: ['A. Lấy phần tử 1 và 3', 'B. Cắt danh sách từ chỉ số 1 đến 2', 'C. Thay đổi phần tử 1 thành 3', 'D. Xóa từ 1 đến 3'], correctOption: 1 },
      { id: 'py_l3_7', question: 'Kiểu dữ liệu Tuple khác List ở điểm nào?', options: ['A. Tuple dùng ngoặc vuông', 'B. Tuple không thể thay đổi giá trị (immutable)', 'C. Tuple nhanh hơn List', 'D. B và C đúng'], correctOption: 3 },
      { id: 'py_l3_8', question: 'Để tạo một Dictionary, ta dùng dấu gì?', options: ['A. []', 'B. ()', 'C. {}', 'D. <>'], correctOption: 2 },
      { id: 'py_l3_9', question: 'Dictionary lưu trữ dữ liệu theo dạng nào?', options: ['A. Chỉ số', 'B. Key - Value', 'C. Ngẫu nhiên', 'D. Thứ tự chữ cái'], correctOption: 1 },
      { id: 'py_l3_10', question: 'Để lấy tất cả các khóa (keys) của dictionary, ta dùng?', options: ['A. keys()', 'B. all_keys()', 'C. get_keys()', 'D. names()'], correctOption: 0 },
      { id: 'py_l3_11', question: 'Lệnh pop() trong List mặc định xóa phần tử nào?', options: ['A. Đầu tiên', 'B. Cuối cùng', 'C. Ngẫu nhiên', 'D. Không xóa gì'], correctOption: 1 },
      { id: 'py_l3_12', question: 'Để sắp xếp một danh sách tăng dần, ta dùng?', options: ['A. organize()', 'B. sort()', 'C. order()', 'D. arrange()'], correctOption: 1 },
      { id: 'py_l3_13', question: 'Lệnh "hello"[0] trả về kết quả gì?', options: ['A. h', 'B. H', 'C. hello', 'D. Lỗi'], correctOption: 0 },
      { id: 'py_l3_14', question: 'Làm thế nào để đảo ngược một chuỗi s?', options: ['A. s.reverse()', 'B. s[::-1]', 'C. reverse(s)', 'D. s[0:-1]'], correctOption: 1 },
      { id: 'py_l3_15', question: 'Hàm split() dùng để làm gì?', options: ['A. Nối chuỗi', 'B. Chia chuỗi thành danh sách', 'C. Xóa khoảng trắng', 'D. Viết hoa chuỗi'], correctOption: 1 },
      { id: 'py_l3_16', question: 'Set trong Python có đặc điểm gì?', options: ['A. Có thứ tự', 'B. Chứa các phần tử không trùng lặp', 'C. Truy cập bằng chỉ số', 'D. Dùng ngoặc vuông'], correctOption: 1 },
      { id: 'py_l3_17', question: 'Làm sao để biết "a" có trong dictionary d không?', options: ['A. d.has("a")', 'B. "a" in d', 'C. d.contains("a")', 'D. d["a"] != None'], correctOption: 1 },
      { id: 'py_l3_18', question: 'Lệnh del list[0] làm gì?', options: ['A. Xóa toàn bộ list', 'B. Xóa phần tử đầu tiên', 'C. Xóa giá trị 0', 'D. Báo lỗi'], correctOption: 1 },
      { id: 'py_l3_19', question: 'Kết quả của list(range(3)) là?', options: ['A. [1, 2, 3]', 'B. [0, 1, 2]', 'C. [0, 1, 2, 3]', 'D. (0, 1, 2)'], correctOption: 1 },
      { id: 'py_l3_20', question: 'Hàm nào dùng để gộp các danh sách thành một chuỗi?', options: ['A. merge()', 'B. join()', 'C. connect()', 'D. combine()'], correctOption: 1 },
    ],
    4: [
      { id: 'py_l4_1', question: 'Từ khóa nào dùng để định nghĩa một hàm?', options: ['A. function', 'B. def', 'C. func', 'D. define'], correctOption: 1 },
      { id: 'py_l4_2', question: 'Lệnh nào dùng để trả về giá trị từ hàm?', options: ['A. give', 'B. send', 'C. return', 'D. result'], correctOption: 2 },
      { id: 'py_l4_3', question: 'Tham số của hàm được đặt trong dấu gì?', options: ['A. []', 'B. {}', 'C. ()', 'D. <>'], correctOption: 2 },
      { id: 'py_l4_4', question: 'Biến được định nghĩa trong hàm gọi là?', options: ['A. Biến toàn cục', 'B. Biến cục bộ', 'C. Biến hằng', 'D. Biến tĩnh'], correctOption: 1 },
      { id: 'py_l4_5', question: 'Làm thế nào để gọi hàm có tên "my_func"?', options: ['A. call my_func()', 'B. my_func()', 'C. my_func', 'D. run my_func'], correctOption: 1 },
      { id: 'py_l4_6', question: 'Hàm không có return sẽ trả về giá trị gì?', options: ['A. 0', 'B. False', 'C. None', 'D. Lỗi'], correctOption: 2 },
      { id: 'py_l4_7', question: 'Tham số mặc định của hàm được định nghĩa như thế nào?', options: ['A. def f(a=10):', 'B. def f(a:10):', 'C. def f(a==10):', 'D. def f(a default 10):'], correctOption: 0 },
      { id: 'py_l4_8', question: 'Làm thế nào để nhập một module vào chương trình?', options: ['A. include', 'B. import', 'C. using', 'D. require'], correctOption: 1 },
      { id: 'py_l4_9', question: 'Module "math" dùng để làm gì?', options: ['A. Vẽ đồ họa', 'B. Tính toán toán học', 'C. Xử lý chuỗi', 'D. Kết nối mạng'], correctOption: 1 },
      { id: 'py_l4_10', question: 'Để lấy căn bậc hai trong module math, ta dùng?', options: ['A. math.sqrt()', 'B. math.pow()', 'C. math.root()', 'D. math.sq()'], correctOption: 0 },
      { id: 'py_l4_11', question: 'Hàm lambda là gì?', options: ['A. Hàm có tên dài', 'B. Hàm ẩn danh (anonymous function)', 'C. Hàm lặp vô hạn', 'D. Một kiểu thư viện'], correctOption: 1 },
      { id: 'py_l4_12', question: 'Lệnh from math import pi có nghĩa là gì?', options: ['A. Nhập toàn bộ module math', 'B. Chỉ nhập giá trị pi từ math', 'C. Đổi tên math thành pi', 'D. Lỗi cú pháp'], correctOption: 1 },
      { id: 'py_l4_13', question: 'Cách dùng hàm "pow(2, 3)" trả về?', options: ['A. 5', 'B. 6', 'C. 8', 'D. 9'], correctOption: 2 },
      { id: 'py_l4_14', question: 'Để cài đặt thư viện mới cho Python, ta dùng công cụ?', options: ['A. apt', 'B. npm', 'C. pip', 'D. brew'], correctOption: 2 },
      { id: 'py_l4_15', question: 'Hàm random.randint(1, 10) làm gì?', options: ['A. Lấy số thực từ 1 đến 10', 'B. Lấy số nguyên ngẫu nhiên từ 1 đến 10', 'C. Sắp xếp từ 1 đến 10', 'D. Lấy số 1 hoặc 10'], correctOption: 1 },
      { id: 'py_l4_16', question: 'Để mở một file để đọc, ta dùng hàm?', options: ['A. read()', 'B. open(filename, "r")', 'C. getFile()', 'D. load()'], correctOption: 1 },
      { id: 'py_l4_17', question: 'Từ khóa global dùng để làm gì?', options: ['A. Tạo biến cho toàn thế giới', 'B. Truy cập biến toàn cục trong hàm', 'C. Kết nối internet', 'D. Khai báo thư viện'], correctOption: 1 },
      { id: 'py_l4_18', question: 'Hàm map() dùng để làm gì?', options: ['A. Vẽ bản đồ', 'B. Áp dụng hàm lên từng phần tử của danh sách', 'C. Tìm kiếm vị trí', 'D. Lọc dữ liệu'], correctOption: 1 },
      { id: 'py_l4_19', question: 'Lệnh "with open(...) as f" có ưu điểm gì?', options: ['A. Chạy nhanh hơn', 'B. Tự động đóng file sau khi dùng', 'C. Mã hóa file', 'D. Không cần quyền admin'], correctOption: 1 },
      { id: 'py_l4_20', question: 'Hàm filter() trả về kết quả khi nào?', options: ['A. Khi hàm điều kiện trả về True', 'B. Luôn trả về mọi thứ', 'C. Khi file bị lỗi', 'D. Khi biến là số nguyên'], correctOption: 0 },
    ],
    5: [
      { id: 'py_l5_1', question: 'Lập trình hướng đối tượng (OOP) dựa trên khái niệm nào?', options: ['A. Hàm và Biến', 'B. Lớp (Class) và Đối tượng (Object)', 'C. Danh sách và Từ điển', 'D. Vòng lặp và Điều kiện'], correctOption: 1 },
      { id: 'py_l5_2', question: 'Từ khóa để định nghĩa một lớp là?', options: ['A. object', 'B. class', 'C. define', 'D. structure'], correctOption: 1 },
      { id: 'py_l5_3', question: 'Phương thức __init__ dùng để làm gì?', options: ['A. Kết thúc lớp', 'B. Khởi tạo đối tượng (Constructor)', 'C. In dữ liệu lớp', 'D. Xóa đối tượng'], correctOption: 1 },
      { id: 'py_l5_4', question: 'Tham số "self" trong phương thức lớp đại diện cho?', options: ['A. Lớp cha', 'B. Chính thực thể đối tượng đó', 'C. Một biến ngẫu nhiên', 'D. Toàn bộ chương trình'], correctOption: 1 },
      { id: 'py_l5_5', question: 'Kế thừa (Inheritance) trong Python được viết như thế nào?', options: ['A. class Child extends Parent:', 'B. class Child(Parent):', 'C. class Child implements Parent:', 'D. class Child -> Parent:'], correctOption: 1 },
      { id: 'py_l5_6', question: 'Để xử lý ngoại lệ (lỗi) trong Python, ta dùng khối lệnh?', options: ['A. if/else', 'B. try/except', 'C. catch/throw', 'D. error/fix'], correctOption: 1 },
      { id: 'py_l5_7', question: 'Lệnh "raise" dùng để làm gì?', options: ['A. Tăng giá trị biến', 'B. Chủ động tạo ra một ngoại lệ', 'C. Kết thúc hàm', 'D. Khởi động lại máy'], correctOption: 1 },
      { id: 'py_l5_8', question: 'Khối lệnh "finally" trong try/except sẽ chạy khi nào?', options: ['A. Chỉ khi có lỗi', 'B. Chỉ khi không có lỗi', 'C. Luôn luôn chạy dù có lỗi hay không', 'D. Không bao giờ chạy'], correctOption: 2 },
      { id: 'py_l5_9', question: 'List Comprehension [x*x for x in range(3)] trả về?', options: ['A. [1, 4, 9]', 'B. [0, 1, 4]', 'C. [0, 1, 2]', 'D. [1, 2, 3]'], correctOption: 1 },
      { id: 'py_l5_10', question: 'Phương thức "super()" dùng để làm gì?', options: ['A. Gọi phương thức của lớp cha', 'B. Tạo đối tượng siêu cấp', 'C. Kết thúc chương trình', 'D. Tăng tốc độ code'], correctOption: 0 },
      { id: 'py_l5_11', question: 'Đa hình (Polymorphism) là gì?', options: ['A. Một đối tượng có nhiều hình dạng', 'B. Nhiều hàm có cùng tên nhưng xử lý khác nhau', 'C. Khả năng kế thừa nhiều lớp', 'D. Cả A và B'], correctOption: 3 },
      { id: 'py_l5_12', question: 'Encapsulation (Đóng gói) nhằm mục đích gì?', options: ['A. Che giấu thông tin chi tiết và bảo vệ dữ liệu', 'B. Nén code lại cho nhỏ', 'C. Gửi dữ liệu qua mạng', 'D. Tạo file thực thi'], correctOption: 0 },
      { id: 'py_l5_13', question: 'Biến có dấu gạch dưới phía trước (ví dụ _name) ám chỉ điều gì?', options: ['A. Biến hằng', 'B. Biến nội bộ/riêng tư (private/protected) theo quy ước', 'C. Biến bị lỗi', 'D. Biến hệ thống'], correctOption: 1 },
      { id: 'py_l5_14', question: 'Decorator trong Python bắt đầu bằng ký hiệu nào?', options: ['A. #', 'B. @', 'C. &', 'D. $'], correctOption: 1 },
      { id: 'py_l5_15', question: 'Hàm zip() dùng để làm gì?', options: ['A. Nén file', 'B. Kết hợp các danh sách thành các cặp phần tử', 'C. Giải nén dữ liệu', 'D. Mã hóa chuỗi'], correctOption: 1 },
      { id: 'py_l5_16', question: 'Lệnh generator "yield" khác gì "return"?', options: ['A. yield nhanh hơn', 'B. yield tạm dừng và lưu trạng thái hàm để tiếp tục sau', 'C. yield chỉ dùng cho số', 'D. yield không trả về giá trị'], correctOption: 1 },
      { id: 'py_l5_17', question: 'Kiểu dữ liệu "None" đại diện cho?', options: ['A. Số 0', 'B. Chuỗi rỗng', 'C. Sự vắng mặt của giá trị', 'D. Giá trị sai'], correctOption: 2 },
      { id: 'py_l5_18', question: 'Làm thế nào để sao chép sâu (deep copy) một đối tượng?', options: ['A. a = b', 'B. a = b.copy()', 'C. Dùng module copy và copy.deepcopy()', 'D. a = list(b)'], correctOption: 2 },
      { id: 'py_l5_19', question: 'Cơ chế Garbage Collection của Python làm gì?', options: ['A. Dọn dẹp code thừa', 'B. Tự động giải phóng bộ nhớ không còn sử dụng', 'C. Quản lý các file rác', 'D. Kiểm tra virus'], correctOption: 1 },
      { id: 'py_l5_20', question: 'Dunder methods (ví dụ __str__) là gì?', options: ['A. Các hàm bị hỏng', 'B. Các phương thức đặc biệt của Python (Magic methods)', 'C. Các biến toàn cục', 'D. Cách viết tên lớp'], correctOption: 1 },
    ]
  },
  [Language.HTML]: {
    1: [
      { id: 'ht_l1_1', question: 'HTML là viết tắt của từ nào?', options: ['A. High Tech Modern Language', 'B. HyperText Markup Language', 'C. Hyperlinks and Text Markup Language', 'D. Home Tool Markup Language'], correctOption: 1 },
      { id: 'ht_l1_2', question: 'Thẻ nào dùng để xác định tiêu đề lớn nhất?', options: ['A. <head>', 'B. <h6>', 'C. <h1>', 'D. <title>'], correctOption: 2 },
      { id: 'ht_l1_3', question: 'Thẻ nào dùng để tạo một đoạn văn?', options: ['A. <paragraph>', 'B. <p>', 'C. <text>', 'D. <div>'], correctOption: 1 },
      { id: 'ht_l1_4', question: 'Thẻ nào dùng để xuống dòng mà không cần đoạn văn mới?', options: ['A. <lb>', 'B. <break>', 'C. <br>', 'D. <next>'], correctOption: 2 },
      { id: 'ht_l1_5', question: 'Thẻ nào là thẻ gốc bao quanh toàn bộ nội dung trang web?', options: ['A. <body>', 'B. <head>', 'C. <html>', 'D. <main>'], correctOption: 2 },
      { id: 'ht_l1_6', question: 'Thẻ <body> dùng để làm gì?', options: ['A. Lưu thông tin cấu hình', 'B. Chứa nội dung hiển thị của trang web', 'C. Định nghĩa tiêu đề trình duyệt', 'D. Chứa các mã script'], correctOption: 1 },
      { id: 'ht_l1_7', question: 'Dấu nào dùng để đóng một thẻ HTML?', options: ['A. /', 'B. \\', 'C. !', 'D. ?'], correctOption: 0 },
      { id: 'ht_l1_8', question: 'Thẻ nào dùng để in đậm văn bản (về mặt ý nghĩa quan trọng)?', options: ['A. <b>', 'B. <bold>', 'C. <strong>', 'D. <i>'], correctOption: 2 },
      { id: 'ht_l1_9', question: 'Thẻ nào dùng để in nghiêng văn bản?', options: ['A. <italic>', 'B. <ins>', 'C. <em>', 'D. <mark>'], correctOption: 2 },
      { id: 'ht_l1_10', question: 'Cặp thẻ nào dùng để định nghĩa phần đầu của tài liệu (chứa meta, title)?', options: ['A. <header>', 'B. <head>', 'C. <top>', 'D. <meta>'], correctOption: 1 },
      { id: 'ht_l1_11', question: 'Phần tử nào hiển thị trên thanh tiêu đề của trình duyệt?', options: ['A. <h1>', 'B. <title>', 'C. <meta>', 'D. <header>'], correctOption: 1 },
      { id: 'ht_l1_12', question: 'Làm thế nào để viết ghi chú (comment) trong HTML?', options: ['A. // ghi chú', 'B. # ghi chú', 'C. <!-- ghi chú -->', 'D. /* ghi chú */'], correctOption: 2 },
      { id: 'ht_l1_13', question: 'Thẻ <hr> dùng để làm gì?', options: ['A. Xuống dòng', 'B. Tạo đường kẻ ngang phân cách', 'C. Chèn hình ảnh', 'D. Tạo liên kết'], correctOption: 1 },
      { id: 'ht_l1_14', question: 'Thẻ nào dùng để gạch chân văn bản?', options: ['A. <underline>', 'B. <u>', 'C. <ins>', 'D. <strike>'], correctOption: 1 },
      { id: 'ht_l1_15', question: 'Đâu là thẻ tự đóng (không có thẻ đóng riêng)?', options: ['A. <p>', 'B. <h1>', 'C. <img>', 'D. <div>'], correctOption: 2 },
      { id: 'ht_l1_16', question: 'Cấu trúc đúng của một thẻ HTML là?', options: ['A. {tag}content{/tag}', 'B. <tag>content</tag>', 'C. [tag]content[/tag]', 'D. <tag>content<tag>'], correctOption: 1 },
      { id: 'ht_l1_17', question: 'Tên file chính của trang web thường là?', options: ['A. main.html', 'B. index.html', 'C. home.html', 'D. web.html'], correctOption: 1 },
      { id: 'ht_l1_18', question: 'Thẻ <h6> so với <h1> thì như thế nào?', options: ['A. Lớn hơn', 'B. Nhỏ hơn', 'C. Bằng nhau', 'D. Đậm hơn'], correctOption: 1 },
      { id: 'ht_l1_19', question: 'Trình duyệt dùng để làm gì?', options: ['A. Viết mã HTML', 'B. Đọc và hiển thị file HTML', 'C. Lưu trữ database', 'D. Chỉnh sửa hình ảnh'], correctOption: 1 },
      { id: 'ht_l1_20', question: 'Khai báo <!DOCTYPE html> dùng để?', options: ['A. Tạo tiêu đề', 'B. Khai báo phiên bản HTML5', 'C. Chèn CSS', 'D. Liên kết Javascript'], correctOption: 1 },
    ],
    2: [
      { id: 'ht_l2_1', question: 'Thẻ nào dùng để tạo một liên kết (hyperlink)?', options: ['A. <link>', 'B. <url>', 'C. <a>', 'D. <href>'], correctOption: 2 },
      { id: 'ht_l2_2', question: 'Thuộc tính nào xác định địa chỉ đích của liên kết?', options: ['A. src', 'B. link', 'C. href', 'D. target'], correctOption: 2 },
      { id: 'ht_l2_3', question: 'Để mở liên kết trong tab mới, ta dùng target nào?', options: ['A. _self', 'B. _new', 'C. _blank', 'D. _parent'], correctOption: 2 },
      { id: 'ht_l2_4', question: 'Thẻ nào dùng để chèn một hình ảnh?', options: ['A. <image>', 'B. <pic>', 'C. <img>', 'D. <source>'], correctOption: 2 },
      { id: 'ht_l2_5', question: 'Thuộc tính nào xác định đường dẫn hình ảnh?', options: ['A. href', 'B. link', 'C. src', 'D. alt'], correctOption: 2 },
      { id: 'ht_l2_6', question: 'Thuộc tính "alt" trong thẻ <img> dùng để làm gì?', options: ['A. Chỉnh kích thước', 'B. Mô tả văn bản thay thế nếu ảnh lỗi', 'C. Tạo tiêu đề ảnh', 'D. Làm ảnh mờ đi'], correctOption: 1 },
      { id: 'ht_l2_7', question: 'Làm thế nào để tạo một liên kết đến email?', options: ['A. <a href="email:abc@gmail.com">', 'B. <a href="mailto:abc@gmail.com">', 'C. <a href="send:abc@gmail.com">', 'D. <a mail="abc@gmail.com">'], correctOption: 1 },
      { id: 'ht_l2_8', question: 'Thuộc tính nào dùng để căn chỉnh độ rộng của phần tử?', options: ['A. size', 'B. length', 'C. width', 'D. height'], correctOption: 2 },
      { id: 'ht_l2_9', question: 'Giá trị mặc định của thuộc tính target là gì?', options: ['A. _blank', 'B. _self', 'C. _top', 'D. _parent'], correctOption: 1 },
      { id: 'ht_l2_10', question: 'Thẻ nào dùng để định nghĩa một khối lớn (block) trên trang?', options: ['A. <span>', 'B. <div>', 'C. <section>', 'D. <block>'], correctOption: 1 },
      { id: 'ht_l2_11', question: 'Sự khác biệt giữa <div> và <span> là gì?', options: ['A. div là block, span là inline', 'B. div là inline, span là block', 'C. Không có sự khác biệt', 'D. div dùng cho ảnh, span dùng cho chữ'], correctOption: 0 },
      { id: 'ht_l2_12', question: 'Thuộc tính "title" trong hầu hết các thẻ dùng để?', options: ['A. Làm tiêu đề trang', 'B. Hiển thị tooltip khi di chuột vào', 'C. Khai báo từ khóa SEO', 'D. Đổi font chữ'], correctOption: 1 },
      { id: 'ht_l2_13', question: 'Để chèn CSS trực tiếp vào thẻ, ta dùng thuộc tính?', options: ['A. class', 'B. id', 'C. style', 'D. css'], correctOption: 2 },
      { id: 'ht_l2_14', question: 'Thuộc tính "class" khác "id" ở điểm nào?', options: ['A. class là duy nhất, id dùng nhiều lần', 'B. id là duy nhất, class dùng nhiều lần', 'C. id dùng cho CSS, class dùng cho JS', 'D. Không khác gì nhau'], correctOption: 1 },
      { id: 'ht_l2_15', question: 'Giá trị nào của width là hợp lệ?', options: ['A. "100px"', 'B. "50%"', 'C. "auto"', 'D. Tất cả đều đúng'], correctOption: 3 },
      { id: 'ht_l2_16', question: 'Thẻ <iframe> dùng để làm gì?', options: ['A. Chèn một trang web khác vào trang hiện tại', 'B. Chèn video Youtube', 'C. Cả A và B', 'D. Tạo khung ảnh'], correctOption: 2 },
      { id: 'ht_l2_17', question: 'Thuộc tính nào quy định ngôn ngữ của trang web (thường ở thẻ html)?', options: ['A. lang', 'B. xml', 'C. code', 'D. speech'], correctOption: 0 },
      { id: 'ht_l2_18', question: 'Đường dẫn tương đối (relative path) là gì?', options: ['A. Đường dẫn đầy đủ có http://', 'B. Đường dẫn dựa trên vị trí file hiện tại', 'C. Đường dẫn trong ổ cứng C:', 'D. Tên file không có đuôi'], correctOption: 1 },
      { id: 'ht_l2_19', question: 'Thẻ <small> dùng để làm gì?', options: ['A. Làm chữ nhỏ đi', 'B. Định nghĩa các bản in nhỏ', 'C. Chứa mã giảm giá', 'D. Cả A và B'], correctOption: 0 },
      { id: 'ht_l2_20', question: 'Thẻ <mark> dùng để làm gì?', options: ['A. Đánh dấu lỗi', 'B. Highlight (tô nền) văn bản', 'C. Tạo danh sách', 'D. Vẽ hình'], correctOption: 1 },
    ],
    3: [
      { id: 'ht_l3_1', question: 'Thẻ nào bắt đầu một danh sách có thứ tự (1, 2, 3)?', options: ['A. <ul>', 'B. <ol>', 'C. <li>', 'D. <list>'], correctOption: 1 },
      { id: 'ht_l3_2', question: 'Thẻ nào bắt đầu một danh sách không thứ tự (dấu chấm tròn)?', options: ['A. <ol>', 'B. <ul>', 'C. <dl>', 'D. <menu>'], correctOption: 1 },
      { id: 'ht_l3_3', question: 'Mỗi mục trong danh sách được bắt đầu bằng thẻ nào?', options: ['A. <item>', 'B. <list-item>', 'C. <li>', 'D. <ol>'], correctOption: 2 },
      { id: 'ht_l3_4', question: 'Thẻ nào dùng để tạo một bảng?', options: ['A. <grid>', 'B. <table>', 'C. <tab>', 'D. <form>'], correctOption: 1 },
      { id: 'ht_l3_5', question: 'Thẻ nào dùng để định nghĩa một hàng trong bảng?', options: ['A. <td>', 'B. <th>', 'C. <tr>', 'D. <row>'], correctOption: 2 },
      { id: 'ht_l3_6', question: 'Thẻ nào dùng để định nghĩa một ô dữ liệu trong bảng?', options: ['A. <tr>', 'B. <th>', 'C. <td>', 'D. <cell>'], correctOption: 2 },
      { id: 'ht_l3_7', question: 'Thẻ nào dùng để định nghĩa ô tiêu đề của bảng (thường in đậm)?', options: ['A. <td>', 'B. <th>', 'C. <thead>', 'D. <header>'], correctOption: 1 },
      { id: 'ht_l3_8', question: 'Thuộc tính nào dùng để gộp nhiều cột trong bảng?', options: ['A. rowspan', 'B. colspan', 'C. merge', 'D. join'], correctOption: 1 },
      { id: 'ht_l3_9', question: 'Thuộc tính nào dùng để gộp nhiều hàng trong bảng?', options: ['A. colspan', 'B. rowspan', 'C. height', 'D. align'], correctOption: 1 },
      { id: 'ht_l3_10', question: 'Thẻ <caption> dùng để làm gì trong bảng?', options: ['A. Đặt tên tiêu đề cho bảng', 'B. Tạo ghi chú dưới bảng', 'C. Đổi màu bảng', 'D. Chèn ảnh vào bảng'], correctOption: 0 },
      { id: 'ht_l3_11', question: 'Để thay đổi kiểu số trong danh sách <ol>, ta dùng thuộc tính?', options: ['A. list-style', 'B. type', 'C. format', 'D. start'], correctOption: 1 },
      { id: 'ht_l3_12', question: 'Danh sách mô tả (Description List) bắt đầu bằng thẻ nào?', options: ['A. <ul>', 'B. <dl>', 'C. <dt>', 'D. <dd>'], correctOption: 1 },
      { id: 'ht_l3_13', question: 'Trong <dl>, thẻ nào dùng để định nghĩa thuật ngữ?', options: ['A. <dt>', 'B. <dd>', 'C. <li>', 'D. <term>'], correctOption: 0 },
      { id: 'ht_l3_14', question: 'Thẻ <thead>, <tbody>, <tfoot> dùng để làm gì?', options: ['A. Phân nhóm các phần của bảng', 'B. Làm bảng chạy nhanh hơn', 'C. Tạo khung cho bảng', 'D. Không có tác dụng gì'], correctOption: 0 },
      { id: 'ht_l3_15', question: 'Làm sao để xóa khoảng cách giữa các ô trong bảng (bằng HTML cũ)?', options: ['A. padding="0"', 'B. cellspacing="0"', 'C. border="0"', 'D. spacing="none"'], correctOption: 1 },
      { id: 'ht_l3_16', question: 'Có thể lồng một danh sách vào trong một mục <li> của danh sách khác không?', options: ['A. Có', 'B. Không', 'C. Chỉ với <ul>', 'D. Chỉ với <ol>'], correctOption: 0 },
      { id: 'ht_l3_17', question: 'Thuộc tính "start" trong <ol> dùng để?', options: ['A. Kết thúc danh sách', 'B. Bắt đầu đánh số từ một số cụ thể', 'C. Tự động chạy', 'D. Đổi màu số'], correctOption: 1 },
      { id: 'ht_l3_18', question: 'Thẻ nào dùng để tạo danh sách các tùy chọn có thể chọn?', options: ['A. <select>', 'B. <option>', 'C. <datalist>', 'D. Cả A và B'], correctOption: 3 },
      { id: 'ht_l3_19', question: 'Làm sao để tạo một đường viền cho bảng (HTML cơ bản)?', options: ['A. border="1"', 'B. stroke="1"', 'C. line="1"', 'D. outline="1"'], correctOption: 0 },
      { id: 'ht_l3_20', question: 'Danh sách không thứ tự có thể đổi kiểu ký hiệu (circle, square) bằng?', options: ['A. type', 'B. list-style-type (CSS)', 'C. style', 'D. Cả B và C'], correctOption: 3 },
    ],
    4: [
      { id: 'ht_l4_1', question: 'Thẻ nào dùng để tạo một biểu mẫu (form) thu thập dữ liệu?', options: ['A. <input>', 'B. <form>', 'C. <collect>', 'D. <action>'], correctOption: 1 },
      { id: 'ht_l4_2', question: 'Phần tử đầu vào phổ biến nhất trong form là?', options: ['A. <textarea>', 'B. <select>', 'C. <input>', 'D. <button>'], correctOption: 2 },
      { id: 'ht_l4_3', question: 'Để tạo ô nhập mật khẩu (ẩn ký tự), type của input là?', options: ['A. secret', 'B. private', 'C. password', 'D. hidden'], correctOption: 2 },
      { id: 'ht_l4_4', question: 'Để tạo nút gửi dữ liệu form đi, type của input là?', options: ['A. button', 'B. send', 'C. submit', 'D. go'], correctOption: 2 },
      { id: 'ht_l4_5', question: 'Để chọn duy nhất một trong nhiều lựa chọn, ta dùng type?', options: ['A. checkbox', 'B. radio', 'C. select', 'D. single'], correctOption: 1 },
      { id: 'ht_l4_6', question: 'Để chọn nhiều lựa chọn cùng lúc, ta dùng type?', options: ['A. multi', 'B. radio', 'C. checkbox', 'D. list'], correctOption: 2 },
      { id: 'ht_l4_7', question: 'Thẻ nào dùng để tạo danh sách thả xuống (dropdown list)?', options: ['A. <dropdown>', 'B. <list>', 'C. <select>', 'D. <input type="list">'], correctOption: 2 },
      { id: 'ht_l4_8', question: 'Để tạo ô nhập văn bản nhiều dòng, ta dùng thẻ?', options: ['A. <input type="text">', 'B. <textbox>', 'C. <textarea>', 'D. <input type="textarea">'], correctOption: 2 },
      { id: 'ht_l4_9', question: 'Thuộc tính "placeholder" dùng để làm gì?', options: ['A. Giữ chỗ cho hình ảnh', 'B. Hiển thị gợi ý mờ trong ô nhập liệu', 'C. Khóa ô nhập liệu', 'D. Tăng độ dài ô nhập'], correctOption: 1 },
      { id: 'ht_l4_10', question: 'Thuộc tính "name" trong input dùng để?', options: ['A. Đặt tên hiển thị', 'B. Định danh dữ liệu khi gửi về server', 'C. Làm đẹp ô nhập', 'D. Tự động điền'], correctOption: 1 },
      { id: 'ht_l4_11', question: 'Thuộc tính "required" có tác dụng gì?', options: ['A. Bắt buộc người dùng phải điền vào ô đó', 'B. Tự động xóa dữ liệu', 'C. Yêu cầu mật khẩu mạnh', 'D. Chỉ cho nhập số'], correctOption: 0 },
      { id: 'ht_l4_12', question: 'Thẻ <label> dùng để làm gì?', options: ['A. Gắn nhãn mô tả cho phần tử input', 'B. Tạo tiêu đề lớn', 'C. Chèn logo', 'D. Tạo danh sách'], correctOption: 0 },
      { id: 'ht_l4_13', question: 'Thuộc tính "action" trong thẻ <form> xác định?', options: ['A. Tên của form', 'B. Nơi gửi dữ liệu form đến', 'C. Phương thức gửi (GET/POST)', 'D. Hiệu ứng của form'], correctOption: 1 },
      { id: 'ht_l4_14', question: 'Thuộc tính "method" trong thẻ <form> thường có giá trị?', options: ['A. SEND/RECEIVE', 'B. GET/POST', 'C. UP/DOWN', 'D. IN/OUT'], correctOption: 1 },
      { id: 'ht_l4_15', question: 'Input type="number" cho phép làm gì?', options: ['A. Nhập mọi ký tự', 'B. Chỉ cho phép nhập số', 'C. Tự động tính toán', 'D. Tạo bảng số'], correctOption: 1 },
      { id: 'ht_l4_16', question: 'Làm thế nào để nhóm các phần tử liên quan trong form?', options: ['A. <div>', 'B. <fieldset>', 'C. <group>', 'D. <section>'], correctOption: 1 },
      { id: 'ht_l4_17', question: 'Thẻ <legend> dùng kèm với <fieldset> để làm gì?', options: ['A. Tạo chú thích cho nhóm', 'B. Tạo danh sách lựa chọn', 'C. Đổi màu khung', 'D. Chèn biểu tượng'], correctOption: 0 },
      { id: 'ht_l4_18', question: 'Sự khác biệt giữa GET và POST?', options: ['A. GET hiển thị dữ liệu trên URL, POST thì không', 'B. GET nhanh hơn POST', 'C. POST bảo mật hơn cho dữ liệu nhạy cảm', 'D. Tất cả đều đúng'], correctOption: 3 },
      { id: 'ht_l4_19', question: 'Làm sao để vô hiệu hóa một ô nhập liệu?', options: ['A. readonly', 'B. disabled', 'C. locked', 'D. stop'], correctOption: 1 },
      { id: 'ht_l4_20', question: 'Input type="file" dùng để làm gì?', options: ['A. Đọc file text', 'B. Cho phép chọn và tải file lên', 'C. Tạo file mới', 'D. Xóa file'], correctOption: 1 },
    ],
    5: [
      { id: 'ht_l5_1', question: 'HTML5 Semantic Elements là gì?', options: ['A. Các thẻ chỉ để làm đẹp', 'B. Các thẻ mang ý nghĩa rõ ràng về cấu trúc (cho cả người và máy)', 'C. Các thẻ dùng để lập trình JS', 'D. Các thẻ cũ bị loại bỏ'], correctOption: 1 },
      { id: 'ht_l5_2', question: 'Thẻ nào dùng để định nghĩa phần đầu của một trang hoặc một phần?', options: ['A. <head>', 'B. <header>', 'C. <top>', 'D. <nav>'], correctOption: 1 },
      { id: 'ht_l5_3', question: 'Thẻ nào chứa các liên kết điều hướng chính?', options: ['A. <navigation>', 'B. <menu>', 'C. <nav>', 'D. <links>'], correctOption: 2 },
      { id: 'ht_l5_4', question: 'Thẻ nào dùng cho nội dung chính độc lập (như bài viết blog)?', options: ['A. <section>', 'B. <main>', 'C. <article>', 'D. <aside>'], correctOption: 2 },
      { id: 'ht_l5_5', question: 'Thẻ nào dùng để nhóm các nội dung liên quan lại với nhau?', options: ['A. <group>', 'B. <section>', 'C. <div>', 'D. <part>'], correctOption: 1 },
      { id: 'ht_l5_6', question: 'Thẻ <aside> thường dùng cho nội dung nào?', options: ['A. Thanh bên (sidebar), nội dung phụ', 'B. Tiêu đề trang', 'C. Chân trang', 'D. Video chính'], correctOption: 0 },
      { id: 'ht_l5_7', question: 'Thẻ nào dùng để định nghĩa chân trang (thông tin liên hệ, bản quyền)?', options: ['A. <bottom>', 'B. <end>', 'C. <footer>', 'D. <base>'], correctOption: 2 },
      { id: 'ht_l5_8', question: 'Thẻ <main> có đặc điểm gì?', options: ['A. Chứa nội dung chính, duy nhất của trang', 'B. Có thể dùng nhiều lần', 'C. Nằm trong thẻ footer', 'D. Chỉ chứa ảnh'], correctOption: 0 },
      { id: 'ht_l5_9', question: 'Thẻ nào dùng để chèn video trong HTML5?', options: ['A. <movie>', 'B. <video>', 'C. <media>', 'D. <embed>'], correctOption: 1 },
      { id: 'ht_l5_10', question: 'Thẻ nào dùng để chèn âm thanh trong HTML5?', options: ['A. <sound>', 'B. <music>', 'C. <audio>', 'D. <voice>'], correctOption: 2 },
      { id: 'ht_l5_11', question: 'Thuộc tính "controls" trong <video> dùng để?', options: ['A. Điều khiển kích thước', 'B. Hiển thị nút Play, Pause, Âm lượng', 'C. Chỉnh màu video', 'D. Tự động chạy'], correctOption: 1 },
      { id: 'ht_l5_12', question: 'Thẻ <canvas> dùng để làm gì?', options: ['A. Chèn ảnh', 'B. Vẽ đồ họa thông qua Javascript', 'C. Tạo hoạt ảnh CSS', 'D. Lưu trữ dữ liệu'], correctOption: 1 },
      { id: 'ht_l5_13', question: 'Thẻ <figure> thường đi kèm với thẻ nào để mô tả ảnh?', options: ['A. <description>', 'B. <figcaption>', 'C. <captions>', 'D. <label>'], correctOption: 1 },
      { id: 'ht_l5_14', question: 'Thẻ <details> kết hợp với <summary> tạo ra hiệu ứng gì?', options: ['A. Danh sách thả xuống', 'B. Nội dung có thể ẩn/hiện (toggle)', 'C. Cửa sổ popup', 'D. Chuyển trang'], correctOption: 1 },
      { id: 'ht_l5_15', question: 'Để nhúng file vector không bị vỡ ảnh, ta dùng thẻ?', options: ['A. <png>', 'B. <svg>', 'C. <canvas>', 'D. <vector>'], correctOption: 1 },
      { id: 'ht_l5_16', question: 'Thẻ <time> dùng để làm gì?', options: ['A. Tạo đồng hồ chạy', 'B. Đánh dấu thời gian để máy tính dễ đọc', 'C. Đếm ngược', 'D. Chỉnh múi giờ'], correctOption: 1 },
      { id: 'ht_l5_17', question: 'Thẻ <progress> dùng để?', options: ['A. Tạo thanh tiến trình hoàn thành', 'B. Tăng tốc trang web', 'C. Kiểm tra dung lượng', 'D. Tải file'], correctOption: 0 },
      { id: 'ht_l5_18', question: 'Thẻ <meter> dùng để làm gì?', options: ['A. Đo lường giá trị trong khoảng (như dung lượng ổ cứng)', 'B. Đo tốc độ mạng', 'C. Đo khoảng cách', 'D. Vẽ biểu đồ cột'], correctOption: 0 },
      { id: 'ht_l5_19', question: 'Web Storage (localStorage) trong HTML5 dùng để?', options: ['A. Lưu trữ dữ liệu lâu dài ở trình duyệt', 'B. Kết nối với SQL Server', 'C. Tăng RAM cho máy', 'D. Bảo mật mật khẩu'], correctOption: 0 },
      { id: 'ht_l5_20', question: 'Thẻ <datalist> dùng để làm gì?', options: ['A. Tạo bảng dữ liệu', 'B. Tạo gợi ý (autocomplete) cho thẻ input', 'C. Lưu danh sách liên hệ', 'D. Kết nối API'], correctOption: 1 },
    ]
  }
};

export const MISSIONS: Record<Language, Mission[]> = {
  [Language.PYTHON]: [
    { id: 'p1', title: 'Lvl 1: Nhập môn', description: 'Lệnh in dữ liệu cơ bản', type: 'quiz', task: 'Hàm nào dùng để xuất dữ liệu ra màn hình?', options: ['echo', 'print', 'show', 'write'], correctOption: 1, difficulty: 'Easy', xpReward: 300, unlocked: true, completed: false, order: 1 },
    { id: 'p2', title: 'Lvl 2: Biến số', description: 'Quy tắc đặt tên biến', type: 'quiz', task: 'Đâu là tên biến HỢP LỆ?', options: ['2variable', 'my-var', 'my_variable', 'my variable'], correctOption: 2, difficulty: 'Easy', xpReward: 400, unlocked: false, completed: false, order: 2 },
    { id: 'p3', title: 'Lvl 3: Kiểu dữ liệu', description: 'Phân biệt Int và String', type: 'quiz', task: 'Kết quả của print(type("10")) là gì?', options: ['int', 'string', 'str', 'float'], correctOption: 2, difficulty: 'Easy', xpReward: 500, unlocked: false, completed: false, order: 3 },
    { id: 'p4', title: 'Lvl 4: Hello World', description: 'Viết dòng code đầu tiên', type: 'code', task: 'Hãy in ra dòng chữ: "Python is magic"', difficulty: 'Easy', xpReward: 600, unlocked: false, completed: false, order: 4 },
    { id: 'p5', title: 'Lvl 5: Toán tử', description: 'Sử dụng biến để tính toán', type: 'code', task: 'Tạo a=10, b=5. In ra kết quả của a nhân b.', difficulty: 'Medium', xpReward: 800, unlocked: false, completed: false, order: 5 },
    { id: 'p6', title: 'Lvl 6: Cấu trúc If', description: 'Câu lệnh điều kiện', type: 'quiz', task: 'Lệnh nào dùng để kiểm tra một điều kiện KHÁC nếu điều kiện đầu sai?', options: ['else', 'elseif', 'elif', 'otherwise'], correctOption: 2, difficulty: 'Medium', xpReward: 900, unlocked: false, completed: false, order: 6 },
    { id: 'p7', title: 'Lvl 7: Danh sách', description: 'Làm việc với List', type: 'quiz', task: 'Để thêm phần tử vào cuối danh sách, ta dùng lệnh gì?', options: ['add()', 'push()', 'insert()', 'append()'], correctOption: 3, difficulty: 'Medium', xpReward: 1000, unlocked: false, completed: false, order: 7 },
    { id: 'p8', title: 'Lvl 8: Kiểm tra tuổi', description: 'Tình huống thực tế với If/Else', type: 'code', task: 'Cho age = 18. Nếu age >= 18 in "Bạn đã trưởng thành", ngược lại in "Bạn còn nhỏ".', difficulty: 'Medium', xpReward: 1200, unlocked: false, completed: false, order: 8 },
    { id: 'p9', title: 'Lvl 9: Vòng lặp For', description: 'Lặp lại hành động', type: 'code', task: 'Sử dụng vòng lặp for để in các số từ 1 đến 5 (dùng hàm range).', difficulty: 'Hard', xpReward: 1500, unlocked: false, completed: false, order: 9 },
    { id: 'p10', title: 'Lvl 10: Bậc Thầy Python', description: 'Giải quyết thuật toán cuối cùng', type: 'code', task: 'Viết một hàm tinh_tong(a, b) trả về tổng của 2 số và in kết quả khi gọi hàm với 5 và 7.', difficulty: 'Hard', xpReward: 2000, unlocked: false, completed: false, order: 10 },
  ],
  [Language.HTML]: [
    { id: 'h1', title: 'Lvl 1: Cấu trúc thẻ', description: 'Nhận diện thẻ HTML', type: 'quiz', task: 'Thẻ nào dùng để tạo tiêu đề quan trọng nhất?', options: ['<head>', '<h1>', '<header>', '<title>'], correctOption: 1, difficulty: 'Easy', xpReward: 300, unlocked: true, completed: false, order: 1 },
    { id: 'h2', title: 'Lvl 2: Thẻ Đoạn Văn', description: 'Trình bày văn bản', type: 'quiz', task: 'Thẻ nào dùng để bắt đầu một đoạn văn?', options: ['<text>', '<p>', '<div>', '<span>'], correctOption: 1, difficulty: 'Easy', xpReward: 400, unlocked: false, completed: false, order: 2 },
    { id: 'h3', title: 'Lvl 3: Thuộc tính', description: 'Bổ sung thông tin cho thẻ', type: 'quiz', task: 'Thuộc tính nào dùng để chỉ đường dẫn hình ảnh cho thẻ <img>?', options: ['href', 'link', 'src', 'alt'], correctOption: 2, difficulty: 'Easy', xpReward: 500, unlocked: false, completed: false, order: 3 },
    { id: 'h4', title: 'Lvl 4: Trang web đầu tiên', description: 'Xây dựng khung trang web', type: 'code', task: 'Tạo một h1 với nội dung "Welcome" và một đoạn văn p mô tả bản thân.', difficulty: 'Easy', xpReward: 600, unlocked: false, completed: false, order: 4 },
    { id: 'h5', title: 'Lvl 5: Danh sách mua sắm', description: 'Sử dụng thẻ List', type: 'code', task: 'Tạo một danh sách không thứ tự (ul) chứa 3 món đồ: Táo, Cam, Chuối.', difficulty: 'Medium', xpReward: 800, unlocked: false, completed: false, order: 5 },
    { id: 'h6', title: 'Lvl 6: Nhập dữ liệu', description: 'Làm việc với Input', type: 'quiz', task: 'Để tạo ô nhập mật khẩu (ẩn ký tự), type của input là gì?', options: ['text', 'hidden', 'password', 'secret'], correctOption: 2, difficulty: 'Medium', xpReward: 900, unlocked: false, completed: false, order: 6 },
    { id: 'h7', title: 'Lvl 7: Thẻ Liên Kết', description: 'Chuyển hướng người dùng', type: 'quiz', task: 'Thẻ nào dùng để tạo một siêu liên kết?', options: ['<link>', '<href>', '<a>', '<url>'], correctOption: 2, difficulty: 'Medium', xpReward: 1000, unlocked: false, completed: false, order: 7 },
    { id: 'h8', title: 'Lvl 8: Bảng dữ liệu', description: 'Trình bày thông tin dạng bảng', type: 'code', task: 'Tạo một table đơn giản gồm 1 hàng và 2 cột: "Họ tên" và "Lớp".', difficulty: 'Medium', xpReward: 1200, unlocked: false, completed: false, order: 8 },
    { id: 'h9', title: 'Lvl 9: Form đăng ký', description: 'Thu thập thông tin', type: 'code', task: 'Tạo một form chứa một nhãn (label) "Email:" và một input type="email".', difficulty: 'Hard', xpReward: 1500, unlocked: false, completed: false, order: 9 },
    { id: 'h10', title: 'Lvl 10: Bậc Thầy Web', description: 'Semantic HTML cuối cùng', type: 'code', task: 'Tạo bố cục trang web gồm thẻ <header>, <main> (chứa một h2) và <footer>.', difficulty: 'Hard', xpReward: 2000, unlocked: false, completed: false, order: 10 },
  ],
};
